repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.5.0
    hooks:
      - id: golangci-lint-full

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: "\\.(ts|tsx|js|jsx|json|css|scss|md|yaml|yml)$"

  - repo: local
    hooks:
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo
        args:
          [
            "clippy",
            "--manifest-path",
            "engine/Cargo.toml",
            "--all-targets",
            "--all-features",
            "--",
            "-D",
            "warnings",
          ]
        language: system
        pass_filenames: false
      - id: ui-tsc
        name: tsc --noEmit
        entry: bash
        args: ["-c", "cd ui && npx tsc --noEmit"]
        language: system
        pass_filenames: false
