repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.58.1
    hooks:
      - id: golangci-lint
        args: ["run", "./..."]
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.3.2
    hooks:
      - id: prettier
        args: ["--check"]
        files: "\\.(ts|tsx|js|jsx|json|css|scss|md|yaml|yml)$"

  - repo: local
    hooks:
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo
        args:
          [
            "clippy",
            "--manifest-path",
            "engine/Cargo.toml",
            "--all-targets",
            "--all-features",
            "--",
            "-D",
            "warnings",
          ]
        language: system
        pass_filenames: false
      - id: ui-tsc
        name: tsc --noEmit
        entry: bash
        args: ["-c", "cd ui && npx tsc --noEmit"]
        language: system
        pass_filenames: false
